DROP TABLE IF EXISTS "public"."T_IPS_HisRunParData_20260601";
CREATE TABLE "public"."T_IPS_HisRunParData_20260601" (
  "F_ID" int8 NOT NULL,
  "F_CreateTime" timestamp(6) NOT NULL,
  "F_Shift" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "F_OrderID" int4 NOT NULL,
  "F_Width" int4 NOT NULL,
  "F_Wave" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_Paper" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CustName" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CustNo" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CutLength" int4,
  "F_CutWidth" int4,
  "F_CustNameD" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CustNoD" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CutLengthD" int4,
  "F_CutWidthD" int4,
  "F_SchMeter" numeric,
  "F_RealPaper" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_CurRemain" numeric NOT NULL,
  "F_Glue_SF1_Form_Factor" numeric,
  "F_Glue_SF2_Form_Factor" numeric,
  "F_Glue_SF3_Form_Factor" numeric,
  "F_Glue_GU_1st_Form_Factor" numeric,
  "F_Glue_GU_2nd_Form_Factor" numeric,
  "F_Glue_GU_3rd_Form_Factor" numeric,
  "F_Glue_GU_1st_Set_Value" numeric,
  "F_Glue_GU_2nd_Set_Value" numeric,
  "F_Glue_GU_3rd_Set_Value" numeric,
  "F_Glue_SF1_Set_Value" numeric,
  "F_Glue_SF2_Set_Value" numeric,
  "F_Glue_SF3_Set_Value" numeric,
  "F_Glue_GU_1st_Get_Value" numeric,
  "F_Glue_GU_2nd_Get_Value" numeric,
  "F_Glue_GU_3rd_Get_Value" numeric,
  "F_Glue_SF1_Get_Value" numeric,
  "F_Glue_SF2_Get_Value" numeric,
  "F_Glue_SF3_Get_Value" numeric,
  "F_Glue_GU_1st_Form_IsOpen" bool NOT NULL,
  "F_Glue_GU_2nd_Form_IsOpen" bool NOT NULL,
  "F_Glue_GU_3rd_Form_IsOpen" bool NOT NULL,
  "F_Glue_SF1_Form_IsOpen" bool NOT NULL,
  "F_Glue_SF2_Form_IsOpen" bool NOT NULL,
  "F_Glue_SF3_Form_IsOpen" bool NOT NULL,
  "F_Glue_SF1_FormQdm_Factor" numeric,
  "F_Glue_SF2_FormQdm_Factor" numeric,
  "F_Glue_SF3_FormQdm_Factor" numeric,
  "F_Glue_GU_1st_FormQdm_Factor" numeric,
  "F_Glue_GU_2nd_FormQdm_Factor" numeric,
  "F_Glue_GU_3rd_FormQdm_Factor" numeric,
  "F_Wrap_GU_0_Form_Factor" numeric,
  "F_Wrap_GU_1st_Form_Factor" numeric,
  "F_Wrap_GU_2nd_Form_Factor" numeric,
  "F_Wrap_GU_3rd_Form_Factor" numeric,
  "F_Wrap_MS1_Form_Factor" numeric,
  "F_Wrap_LS1_Form_Factor" numeric,
  "F_Wrap_MS2_Form_Factor" numeric,
  "F_Wrap_LS2_Form_Factor" numeric,
  "F_Wrap_MS3_Form_Factor" numeric,
  "F_Wrap_LS3_Form_Factor" numeric,
  "F_Wrap_GU_0_Set_Value" numeric,
  "F_Wrap_GU_1st_Set_Value" numeric,
  "F_Wrap_GU_2nd_Set_Value" numeric,
  "F_Wrap_GU_3rd_Set_Value" numeric,
  "F_Wrap_LS1_Set_Value" numeric,
  "F_Wrap_LS2_Set_Value" numeric,
  "F_Wrap_LS3_Set_Value" numeric,
  "F_Wrap_MS1_Set_Value" numeric,
  "F_Wrap_MS2_Set_Value" numeric,
  "F_Wrap_MS3_Set_Value" numeric,
  "F_Wrap_GU_0_Get_Value" numeric,
  "F_Wrap_GU_1st_Get_Value" numeric,
  "F_Wrap_GU_2nd_Get_Value" numeric,
  "F_Wrap_GU_3rd_Get_Value" numeric,
  "F_Wrap_LS1_Get_Value" numeric,
  "F_Wrap_LS2_Get_Value" numeric,
  "F_Wrap_LS3_Get_Value" numeric,
  "F_Wrap_MS1_Get_Value" numeric,
  "F_Wrap_MS2_Get_Value" numeric,
  "F_Wrap_MS3_Get_Value" numeric,
  "F_Wrap_GU_0_FormQdm_Factor" numeric,
  "F_Wrap_GU_1st_FormQdm_Factor" numeric,
  "F_Wrap_GU_2nd_FormQdm_Factor" numeric,
  "F_Wrap_GU_3rd_FormQdm_Factor" numeric,
  "F_Wrap_MS1_FormQdm_Factor" numeric,
  "F_Wrap_LS1_FormQdm_Factor" numeric,
  "F_Wrap_MS2_FormQdm_Factor" numeric,
  "F_Wrap_LS2_FormQdm_Factor" numeric,
  "F_Wrap_MS3_FormQdm_Factor" numeric,
  "F_Wrap_LS3_FormQdm_Factor" numeric,
  "F_Wrap_GU_0_Form_IsOpen" bool NOT NULL,
  "F_Wrap_GU_1st_Form_IsOpen" bool NOT NULL,
  "F_Wrap_GU_2nd_Form_IsOpen" bool NOT NULL,
  "F_Wrap_GU_3rd_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS1_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS2_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS3_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS1_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS2_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS3_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_GU_0_Form_Factor" numeric,
  "F_PreheaterSteam_GU_1st_Form_Factor" numeric,
  "F_PreheaterSteam_GU_2nd_Form_Factor" numeric,
  "F_PreheaterSteam_GU_3rd_Form_Factor" numeric,
  "F_PreheaterSteam_SF1_Form_Factor" numeric,
  "F_PreheaterSteam_SF2_Form_Factor" numeric,
  "F_PreheaterSteam_SF3_Form_Factor" numeric,
  "F_PreheaterSteam_GU_0_Set_Value" numeric,
  "F_PreheaterSteam_GU_1st_Set_Value" numeric,
  "F_PreheaterSteam_GU_2nd_Set_Value" numeric,
  "F_PreheaterSteam_GU_3rd_Set_Value" numeric,
  "F_PreheaterSteam_SF1_Set_Value" numeric,
  "F_PreheaterSteam_SF2_Set_Value" numeric,
  "F_PreheaterSteam_SF3_Set_Value" numeric,
  "F_PreheaterSteam_GU_0_Get_Value" numeric,
  "F_PreheaterSteam_GU_1st_Get_Value" numeric,
  "F_PreheaterSteam_GU_2nd_Get_Value" numeric,
  "F_PreheaterSteam_GU_3rd_Get_Value" numeric,
  "F_PreheaterSteam_SF1_Get_Value" numeric,
  "F_PreheaterSteam_SF2_Get_Value" numeric,
  "F_PreheaterSteam_SF3_Get_Value" numeric,
  "F_PreheaterSteam_GU_0_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_GU_1st_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_GU_2nd_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_GU_3rd_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_SF1_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_SF2_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_SF3_Form_IsOpen" bool NOT NULL,
  "F_PreheaterSteam_GU_0_FormQdm_Factor" numeric,
  "F_PreheaterSteam_GU_1st_FormQdm_Factor" numeric,
  "F_PreheaterSteam_GU_2nd_FormQdm_Factor" numeric,
  "F_PreheaterSteam_GU_3rd_FormQdm_Factor" numeric,
  "F_PreheaterSteam_SF1_FormQdm_Factor" numeric,
  "F_PreheaterSteam_SF2_FormQdm_Factor" numeric,
  "F_PreheaterSteam_SF3_FormQdm_Factor" numeric,
  "F_PressRoll_SF1_OS_Form_Factor" numeric,
  "F_PressRoll_SF1_DS_Form_Factor" numeric,
  "F_PressRoll_SF2_OS_Form_Factor" numeric,
  "F_PressRoll_SF2_DS_Form_Factor" numeric,
  "F_PressRoll_SF3_OS_Form_Factor" numeric,
  "F_PressRoll_SF3_DS_Form_Factor" numeric,
  "F_PressRoll_SF1_OS_Set_Value" numeric,
  "F_PressRoll_SF1_DS_Set_Value" numeric,
  "F_PressRoll_SF2_OS_Set_Value" numeric,
  "F_PressRoll_SF2_DS_Set_Value" numeric,
  "F_PressRoll_SF3_OS_Set_Value" numeric,
  "F_PressRoll_SF3_DS_Set_Value" numeric,
  "F_PressRoll_SF1_OS_Get_Value" numeric,
  "F_PressRoll_SF1_DS_Get_Value" numeric,
  "F_PressRoll_SF2_OS_Get_Value" numeric,
  "F_PressRoll_SF2_DS_Get_Value" numeric,
  "F_PressRoll_SF3_OS_Get_Value" numeric,
  "F_PressRoll_SF3_DS_Get_Value" numeric,
  "F_PressRoll_SF1_Form_IsOpen" bool NOT NULL,
  "F_PressRoll_SF2_Form_IsOpen" bool NOT NULL,
  "F_PressRoll_SF3_Form_IsOpen" bool NOT NULL,
  "F_PressRoll_SF1_OS_FormQdm_Factor" numeric,
  "F_PressRoll_SF1_DS_FormQdm_Factor" numeric,
  "F_PressRoll_SF2_OS_FormQdm_Factor" numeric,
  "F_PressRoll_SF2_DS_FormQdm_Factor" numeric,
  "F_PressRoll_SF3_OS_FormQdm_Factor" numeric,
  "F_PressRoll_SF3_DS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF1_OS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF1_DS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF2_OS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF2_DS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF3_OS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF3_DS_Form_Factor" numeric,
  "F_CorrugatedRoll_SF1_OS_Set_Value" numeric,
  "F_CorrugatedRoll_SF1_DS_Set_Value" numeric,
  "F_CorrugatedRoll_SF2_OS_Set_Value" numeric,
  "F_CorrugatedRoll_SF2_DS_Set_Value" numeric,
  "F_CorrugatedRoll_SF3_OS_Set_Value" numeric,
  "F_CorrugatedRoll_SF3_DS_Set_Value" numeric,
  "F_CorrugatedRoll_SF1_OS_Get_Value" numeric,
  "F_CorrugatedRoll_SF1_DS_Get_Value" numeric,
  "F_CorrugatedRoll_SF2_OS_Get_Value" numeric,
  "F_CorrugatedRoll_SF2_DS_Get_Value" numeric,
  "F_CorrugatedRoll_SF3_OS_Get_Value" numeric,
  "F_CorrugatedRoll_SF3_DS_Get_Value" numeric,
  "F_CorrugatedRoll_SF1_Form_IsOpen" bool NOT NULL,
  "F_CorrugatedRoll_SF2_Form_IsOpen" bool NOT NULL,
  "F_CorrugatedRoll_SF3_Form_IsOpen" bool NOT NULL,
  "F_CorrugatedRoll_SF1_OS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF1_DS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF2_OS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF2_DS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF3_OS_FormQdm_Factor" numeric,
  "F_CorrugatedRoll_SF3_DS_FormQdm_Factor" numeric,
  "F_HotPlateSteam_DF_1Part_Form_Factor" numeric,
  "F_HotPlateSteam_DF_2Part_Form_Factor" numeric,
  "F_HotPlateSteam_DF_3Part_Form_Factor" numeric,
  "F_HotPlateSteam_DF_4Part_Form_Factor" numeric,
  "F_HotPlateSteam_DF_1Part_Set_Value" numeric,
  "F_HotPlateSteam_DF_2Part_Set_Value" numeric,
  "F_HotPlateSteam_DF_3Part_Set_Value" numeric,
  "F_HotPlateSteam_DF_4Part_Set_Value" numeric,
  "F_HotPlateSteam_DF_1Part_Get_Value" numeric,
  "F_HotPlateSteam_DF_2Part_Get_Value" numeric,
  "F_HotPlateSteam_DF_3Part_Get_Value" numeric,
  "F_HotPlateSteam_DF_4Part_Get_Value" numeric,
  "F_HotPlateSteam_DF_1Part_Form_IsOpen" bool NOT NULL,
  "F_HotPlateSteam_DF_2Part_Form_IsOpen" bool NOT NULL,
  "F_HotPlateSteam_DF_3Part_Form_IsOpen" bool NOT NULL,
  "F_HotPlateSteam_DF_4Part_Form_IsOpen" bool NOT NULL,
  "F_HotPlateSteam_DF_1Part_FormQdm_Factor" numeric,
  "F_HotPlateSteam_DF_2Part_FormQdm_Factor" numeric,
  "F_HotPlateSteam_DF_3Part_FormQdm_Factor" numeric,
  "F_HotPlateSteam_DF_4Part_FormQdm_Factor" numeric,
  "F_HotLoadGroupQty_DF_Run_Value" int4,
  "F_HotLoadGroupQty_DF_Form_IsOpen" bool NOT NULL,
  "F_HotPlatePress_DF_Form_Factor" numeric,
  "F_HotPlate1Press_DF_Form_Factor" numeric,
  "F_HotPlate2Press_DF_Form_Factor" numeric,
  "F_HotPlatePress_DF_Set_Value" numeric,
  "F_HotPlate2Press_DF_Set_Value" numeric,
  "F_HotPlate1Press_DF_Set_Value" numeric,
  "F_HotPlatePress_DF_Get_Value" numeric,
  "F_HotPlate2Press_DF_Get_Value" numeric,
  "F_HotPlate1Press_DF_Get_Value" numeric,
  "F_HotPlatePress_DF_Form_IsOpen" bool NOT NULL,
  "F_HotPlate2Press_DF_Form_IsOpen" bool,
  "F_HotPlate1Press_DF_Form_IsOpen" bool,
  "F_HotPlatePress_DF_FormQdm_Factor" numeric,
  "F_HotPlate1Press_DF_FormQdm_Factor" numeric,
  "F_HotPlate2Press_DF_FormQdm_Factor" numeric,
  "F_ColdPlatePress_DF_Form_Factor" numeric,
  "F_ColdPlatePress_DF_Set_Value" numeric,
  "F_ColdPlatePress_DF_Get_Value" numeric,
  "F_ColdPlatePress_DF_Form_IsOpen" bool NOT NULL,
  "F_ColdPlatePress_DF_FormQdm_Factor" numeric,
  "F_SplicerTension_LS0_Form_Factor" numeric,
  "F_SplicerTension_LS1_Form_Factor" numeric,
  "F_SplicerTension_LS2_Form_Factor" numeric,
  "F_SplicerTension_LS3_Form_Factor" numeric,
  "F_SplicerTension_MS1_Form_Factor" numeric,
  "F_SplicerTension_MS2_Form_Factor" numeric,
  "F_SplicerTension_MS3_Form_Factor" numeric,
  "F_SplicerTension_LS0_Set_Value" numeric,
  "F_SplicerTension_LS1_Set_Value" numeric,
  "F_SplicerTension_LS2_Set_Value" numeric,
  "F_SplicerTension_LS3_Set_Value" numeric,
  "F_SplicerTension_MS1_Set_Value" numeric,
  "F_SplicerTension_MS2_Set_Value" numeric,
  "F_SplicerTension_MS3_Set_Value" numeric,
  "F_SplicerTension_LS0_Get_Value" numeric,
  "F_SplicerTension_LS1_Get_Value" numeric,
  "F_SplicerTension_LS2_Get_Value" numeric,
  "F_SplicerTension_LS3_Get_Value" numeric,
  "F_SplicerTension_MS1_Get_Value" numeric,
  "F_SplicerTension_MS2_Get_Value" numeric,
  "F_SplicerTension_MS3_Get_Value" numeric,
  "F_SplicerTension_LS0_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_LS0_FormQdm_Factor" numeric,
  "F_SplicerTension_LS1_FormQdm_Factor" numeric,
  "F_SplicerTension_LS2_FormQdm_Factor" numeric,
  "F_SplicerTension_LS3_FormQdm_Factor" numeric,
  "F_SplicerTension_MS1_FormQdm_Factor" numeric,
  "F_SplicerTension_MS2_FormQdm_Factor" numeric,
  "F_SplicerTension_MS3_FormQdm_Factor" numeric,
  "F_BridgeTension_GU_1st_Form_Factor" numeric,
  "F_BridgeTension_GU_2nd_Form_Factor" numeric,
  "F_BridgeTension_GU_3rd_Form_Factor" numeric,
  "F_BridgeTension_GU_1st_Set_Value" numeric,
  "F_BridgeTension_GU_2nd_Set_Value" numeric,
  "F_BridgeTension_GU_3rd_Set_Value" numeric,
  "F_BridgeTension_GU_1st_Get_Value" numeric,
  "F_BridgeTension_GU_2nd_Get_Value" numeric,
  "F_BridgeTension_GU_3rd_Get_Value" numeric,
  "F_SplicerTension_MS1_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_LS1_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_MS2_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_LS2_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_MS3_Form_IsOpen" bool NOT NULL,
  "F_SplicerTension_LS3_Form_IsOpen" bool NOT NULL,
  "F_BridgeTension_GU_1st_Form_IsOpen" bool NOT NULL,
  "F_BridgeTension_GU_2nd_Form_IsOpen" bool NOT NULL,
  "F_BridgeTension_GU_3rd_Form_IsOpen" bool NOT NULL,
  "F_BridgeTension_GU_1st_FormQdm_Factor" numeric,
  "F_BridgeTension_GU_2nd_FormQdm_Factor" numeric,
  "F_BridgeTension_GU_3rd_FormQdm_Factor" numeric,
  "F_CruisingSpeed_DF_Form_Factor" numeric,
  "F_CruisingSpeed_DF_CMD" bool NOT NULL,
  "F_CruisingSpeed_SF1_CMD" bool NOT NULL,
  "F_CruisingSpeed_SF2_CMD" bool NOT NULL,
  "F_CruisingSpeed_SF3_CMD" bool NOT NULL,
  "F_CruisingSpeed_DF_Set_Value" numeric,
  "F_CruisingSpeed_SF1_Set_Value" int4,
  "F_CruisingSpeed_SF2_Set_Value" int4,
  "F_CruisingSpeed_SF3_Set_Value" int4,
  "F_CruisingSpeed_IsUseNew" bool NOT NULL,
  "F_CruiseNotAuto" bool,
  "F_Remainmm_LS0" numeric,
  "F_Remainmm_LS1" numeric,
  "F_Remainmm_LS2" numeric,
  "F_Remainmm_LS3" numeric,
  "F_Remainmm_MS1" numeric,
  "F_Remainmm_MS2" numeric,
  "F_Remainmm_MS3" numeric,
  "F_Remainm_LS0" numeric,
  "F_Remainm_LS1" numeric,
  "F_Remainm_LS2" numeric,
  "F_Remainm_LS3" numeric,
  "F_Remainm_MS1" numeric,
  "F_Remainm_MS2" numeric,
  "F_Remainm_MS3" numeric,
  "F_CruisingSpeed_ALL_Form_IsOpen" bool NOT NULL,
  "F_CruisingSpeed_DF_Form_IsOpen" bool NOT NULL,
  "F_CruisingSpeed_SF1_Form_IsOpen" bool NOT NULL,
  "F_CruisingSpeed_SF2_Form_IsOpen" bool NOT NULL,
  "F_CruisingSpeed_SF3_Form_IsOpen" bool NOT NULL,
  "F_Cruising_IsUsing" bool NOT NULL,
  "F_SpeedDF" int4,
  "F_SpeedSF1" int4,
  "F_SpeedSF2" int4,
  "F_SpeedSF3" int4,
  "F_SpeedLS0" int4,
  "F_SpeedMS1" int4,
  "F_SpeedLS1" int4,
  "F_SpeedMS2" int4,
  "F_SpeedLS2" int4,
  "F_SpeedMS3" int4,
  "F_SpeedLS3" int4,
  "F_WebOnBridgeSF1" int4,
  "F_WebOnBridgeSF2" int4,
  "F_WebOnBridgeSF3" int4,
  "F_WebOnBridgeStateSF1" int4,
  "F_WebOnBridgeStateSF2" int4,
  "F_WebOnBridgeStateSF3" int4,
  "F_SpliceToggle_LS0" bool NOT NULL,
  "F_SpliceToggle_MS1" bool NOT NULL,
  "F_SpliceToggle_LS1" bool NOT NULL,
  "F_SpliceToggle_MS2" bool NOT NULL,
  "F_SpliceToggle_LS2" bool NOT NULL,
  "F_SpliceToggle_MS3" bool NOT NULL,
  "F_SpliceToggle_LS3" bool NOT NULL,
  "F_SF1_DistanceTillLsSpliceAtPressureRoll" numeric,
  "F_SF1_DistanceTillMsSpliceAtPressureRoll" numeric,
  "F_SF2_DistanceTillLsSpliceAtPressureRoll" numeric,
  "F_SF2_DistanceTillMsSpliceAtPressureRoll" numeric,
  "F_SF3_DistanceTillLsSpliceAtPressureRoll" numeric,
  "F_SF3_DistanceTillMsSpliceAtPressureRoll" numeric,
  "F_BatterLevelGU1" int4,
  "F_BatterLevelGU2" int4,
  "F_BatterLevelGU3" int4,
  "F_BatterLevelSF1" int4,
  "F_BatterLevelSF2" int4,
  "F_BatterLevelSF3" int4,
  "F_LowTankPressure" numeric,
  "F_HighTankPressure" numeric,
  "F_RidingRoll_1st_Set_Value" numeric,
  "F_RidingRoll_2nd_Set_Value" numeric,
  "F_RidingRoll_3rd_Set_Value" numeric,
  "F_RidingRoll_1st_Get_Value" numeric,
  "F_RidingRoll_2nd_Get_Value" numeric,
  "F_RidingRoll_3rd_Get_Value" numeric,
  "F_RidingRoll_1st_Form_IsOpen" bool NOT NULL,
  "F_RidingRoll_2nd_Form_IsOpen" bool NOT NULL,
  "F_RidingRoll_3rd_Form_IsOpen" bool NOT NULL,
  "F_RidingRoll_1st_Form_Factor" numeric,
  "F_RidingRoll_2nd_Form_Factor" numeric,
  "F_RidingRoll_3rd_Form_Factor" numeric,
  "F_Warp_Form_IsOpen" bool NOT NULL,
  "F_Warp_DetectState" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_Warp_DetectDegree" numeric,
  "F_Warp_ExecuteState" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "F_WrapTemperature_GU_0_Set_Value" numeric,
  "F_WrapTemperature_GU_1st_Set_Value" numeric,
  "F_WrapTemperature_GU_2nd_Set_Value" numeric,
  "F_WrapTemperature_GU_3rd_Set_Value" numeric,
  "F_WrapTemperature_LS1_Set_Value" numeric,
  "F_WrapTemperature_LS2_Set_Value" numeric,
  "F_WrapTemperature_LS3_Set_Value" numeric,
  "F_WrapTemperature_MS1_Set_Value" numeric,
  "F_WrapTemperature_MS2_Set_Value" numeric,
  "F_WrapTemperature_MS3_Set_Value" numeric,
  "F_WrapTemperature_GU_0_Get_Value" numeric,
  "F_WrapTemperature_GU_1st_Get_Value" numeric,
  "F_WrapTemperature_GU_2nd_Get_Value" numeric,
  "F_WrapTemperature_GU_3rd_Get_Value" numeric,
  "F_WrapTemperature_LS1_Get_Value" numeric,
  "F_WrapTemperature_LS2_Get_Value" numeric,
  "F_WrapTemperature_LS3_Get_Value" numeric,
  "F_WrapTemperature_MS1_Get_Value" numeric,
  "F_WrapTemperature_MS2_Get_Value" numeric,
  "F_WrapTemperature_MS3_Get_Value" numeric,
  "F_WrapTemperature_GU_IsUse" bool NOT NULL,
  "F_WrapTemperature_SF1_IsUse" bool NOT NULL,
  "F_WrapTemperature_SF2_IsUse" bool NOT NULL,
  "F_WrapTemperature_SF3_IsUse" bool NOT NULL,
  "F_WrapTemperature_GU_0_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_GU_1st_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_GU_2nd_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_GU_3rd_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_LS1_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_LS2_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_LS3_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_MS1_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_MS2_Form_IsOpen" bool NOT NULL,
  "F_WrapTemperature_MS3_Form_IsOpen" bool NOT NULL,
  "F_Wrap_GU_Ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS1ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS1ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS2ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS2ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_MS3ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_LS3ext_Form_IsOpen" bool NOT NULL,
  "F_Wrap_GU_Ext_Form_Factor" numeric,
  "F_Wrap_MS1ext_Form_Factor" numeric,
  "F_Wrap_LS1ext_Form_Factor" numeric,
  "F_Wrap_MS2ext_Form_Factor" numeric,
  "F_Wrap_LS2ext_Form_Factor" numeric,
  "F_Wrap_MS3ext_Form_Factor" numeric,
  "F_Wrap_LS3ext_Form_Factor" numeric,
  "F_Wrap_GU_Ext_FormQdm_Factor" numeric,
  "F_Wrap_MS1ext_FormQdm_Factor" numeric,
  "F_Wrap_LS1ext_FormQdm_Factor" numeric,
  "F_Wrap_MS2ext_FormQdm_Factor" numeric,
  "F_Wrap_LS2ext_FormQdm_Factor" numeric,
  "F_Wrap_MS3ext_FormQdm_Factor" numeric,
  "F_Wrap_LS3ext_FormQdm_Factor" numeric,
  "F_Wrap_GU_Ext_Set_Value" numeric,
  "F_Wrap_MS1ext_Set_Value" numeric,
  "F_Wrap_LS1ext_Set_Value" numeric,
  "F_Wrap_MS2ext_Set_Value" numeric,
  "F_Wrap_LS2ext_Set_Value" numeric,
  "F_Wrap_MS3ext_Set_Value" numeric,
  "F_Wrap_LS3ext_Set_Value" numeric,
  "F_Wrap_GU_Ext_Get_Value" numeric,
  "F_Wrap_MS1ext_Get_Value" numeric,
  "F_Wrap_LS1ext_Get_Value" numeric,
  "F_Wrap_MS2ext_Get_Value" numeric,
  "F_Wrap_LS2ext_Get_Value" numeric,
  "F_Wrap_MS3ext_Get_Value" numeric,
  "F_Wrap_LS3ext_Get_Value" numeric,
  "F_BlcDF" bool,
  "F_BlcSF1" bool,
  "F_BlcSF2" bool,
  "F_BlcSF3" bool,
  "F_Glue_SF1_Qdm_Factor" numeric,
  "F_Glue_SF2_Qdm_Factor" numeric,
  "F_Glue_SF3_Qdm_Factor" numeric,
  "F_Glue_GU_1st_Qdm_Factor" numeric,
  "F_Glue_GU_2nd_Qdm_Factor" numeric,
  "F_Glue_GU_3rd_Qdm_Factor" numeric,
  "F_Wrap_GU_0_Qdm_Factor" numeric,
  "F_Wrap_GU_1st_Qdm_Factor" numeric,
  "F_Wrap_GU_2nd_Qdm_Factor" numeric,
  "F_Wrap_GU_3rd_Qdm_Factor" numeric,
  "F_Wrap_MS1_Qdm_Factor" numeric,
  "F_Wrap_LS1_Qdm_Factor" numeric,
  "F_Wrap_MS2_Qdm_Factor" numeric,
  "F_Wrap_LS2_Qdm_Factor" numeric,
  "F_Wrap_MS3_Qdm_Factor" numeric,
  "F_Wrap_LS3_Qdm_Factor" numeric,
  "F_PreheaterSteam_GU_0_Qdm_Factor" numeric,
  "F_PreheaterSteam_GU_1st_Qdm_Factor" numeric,
  "F_PreheaterSteam_GU_2nd_Qdm_Factor" numeric,
  "F_PreheaterSteam_GU_3rd_Qdm_Factor" numeric,
  "F_PreheaterSteam_SF1_Qdm_Factor" numeric,
  "F_PreheaterSteam_SF2_Qdm_Factor" numeric,
  "F_PreheaterSteam_SF3_Qdm_Factor" numeric,
  "F_PressRoll_SF1_OS_Qdm_Factor" numeric,
  "F_PressRoll_SF1_DS_Qdm_Factor" numeric,
  "F_PressRoll_SF2_OS_Qdm_Factor" numeric,
  "F_PressRoll_SF2_DS_Qdm_Factor" numeric,
  "F_PressRoll_SF3_OS_Qdm_Factor" numeric,
  "F_PressRoll_SF3_DS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF1_OS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF1_DS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF2_OS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF2_DS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF3_OS_Qdm_Factor" numeric,
  "F_CorrugatedRoll_SF3_DS_Qdm_Factor" numeric,
  "F_HotPlateSteam_DF_1Part_Qdm_Factor" numeric,
  "F_HotPlateSteam_DF_2Part_Qdm_Factor" numeric,
  "F_HotPlateSteam_DF_3Part_Qdm_Factor" numeric,
  "F_HotPlatePress_DF_Qdm_Factor" numeric,
  "F_HotPlate1Press_DF_Qdm_Factor" numeric,
  "F_HotPlate2Press_DF_Qdm_Factor" numeric,
  "F_ColdPlatePress_DF_Qdm_Factor" numeric,
  "F_SplicerTension_LS0_Qdm_Factor" numeric,
  "F_SplicerTension_LS1_Qdm_Factor" numeric,
  "F_SplicerTension_MS1_Qdm_Factor" numeric,
  "F_SplicerTension_LS2_Qdm_Factor" numeric,
  "F_SplicerTension_MS2_Qdm_Factor" numeric,
  "F_SplicerTension_LS3_Qdm_Factor" numeric,
  "F_SplicerTension_MS3_Qdm_Factor" numeric,
  "F_BridgeTension_GU_1st_Qdm_Factor" numeric,
  "F_BridgeTension_GU_2nd_Qdm_Factor" numeric,
  "F_BridgeTension_GU_3rd_Qdm_Factor" numeric,
  "F_Wrap_GU_Ext_Qdm_Factor" numeric,
  "F_Wrap_MS1ext_Qdm_Factor" numeric,
  "F_Wrap_LS1ext_Qdm_Factor" numeric,
  "F_Wrap_MS2ext_Qdm_Factor" numeric,
  "F_Wrap_LS2ext_Qdm_Factor" numeric,
  "F_Wrap_MS3ext_Qdm_Factor" numeric,
  "F_Wrap_LS3ext_Qdm_Factor" numeric,
  "F_HotPlateSteam_DF_4Part_Qdm_Factor" numeric,
  "F_HotLoadGroupQty_DF_Qdm_Factor" numeric,
  "F_HotLoadGroupQty_DF_FormQdm_Factor" numeric,
  "F_HotLoadGroupQty_DF_Form_Factor" numeric,
  "F_DualBoost1_Get_Value" numeric,
  "F_DualBoost2_Get_Value" numeric,
  "F_RealPaperListJson" Text
)
;